### ISSUE TITLE
Perfomance Degradation 

### ISSUE THREAD

**Issue by neomonkeus** [niftools/max_nif_plugin#2]
Models which I export from 3ds Max cause terrifying slowdowns in game.
It can be fixed by importing these models to Blender and re-exporting them to .nif again without any changes. Proofshots (first - original model, second - re-exported; compare FPS-counter!):
http://s54.radikal.ru/i145/1001/00/a9b019e65334.jpg
http://s53.radikal.ru/i142/1001/d9/270b391ccefb.jpg

Slowdowns have been found on 3 PC's with different configurations (GF8800, GF7600, Radeon4890, Intel & AMD CPU's etc).

I found this by accident not too long ago, but after some checks I can confirm that EVERY my model exported from 3ds Max since February 2007 or even earlier has this flaw. Since 2007 I many times changed 3ds Max, MaxPlugins and even OS, so... something really wrong. :(

WinXP \ Win7 x64, 3ds Max 8 - 2008, MaxPlugins 0.2.10 - 3.5.5 (this version I compiled myself with VS2008 for Max2008).

**Comment by blabbatheorange** [comment]
This was probably some error in the older versions. This issue is currently non-existent.

**Comment by neomonkeus** [comment]
Could have been a tristripes related issue on older hardware perhaps.
