### ISSUE TITLE
Bones import incorrectly : Tail rotation

### ISSUE THREAD

**Issue by neomonkeus** [niftools/max_nif_plugin#8]
Hi. 
Prometeus and I found that many bones are not correctly imported in 3dsmax. The bone objects seems to have a -90 y axis rotation shift from the link line. I've already tried to fix this manualy whitin 3dmax but I get weird result with some bones. It's a real pain and make things actualy nearly unusable for rigging / skinnig / animation. It would greatly help if this could be fixed.
I'm currently using niftools-max-plugins-3.7.1.fdef17d with 3dsmax2012 (64bits)
(to track) Bug procedure:
1. Import the file skeleton.nif (file attached) into 3dsmax2012 (this will display link lines only so follow next steps...)
2. Select all the skeleton hierarachy in viewport (or with select dialog)
3. Go to display tab to uncheck "replace object by link" (to display bones objects in viewport)

Bones now display in the viewport but many of them aren't aligned correctely (their x local axis should follow the link lines)
Best regards.

**Comment by neomonkeus** [comment]
https://www.dropbox.com/s/tydordjjrnor0qz/skeleton.nif?dl=0

**Comment by blabbatheorange** [comment]
This is not a problem with the latest version.

**Comment by neomonkeus** [comment]
@blabbatheorange - This is a migrated issue from sf.net.
Can you confirm what you mean by latest, i.e is this issue resolved in the latest code on dev branch?

**Comment by blabbatheorange** [comment]
Yeap, bones have 100% correct rotations and data, which is why it's possible to skin clothing/armour correctly. The user may have been confused between parent space and local space (nifskope shows bones in parent space, not local space). Following the outlined steps I'm able to retrieve all skeleton bones just fine with code from the dev branch.

**Comment by neomonkeus** [comment]
Cheers @blabbatheorange.
Most of the issues written my me are "migrated" issues so hopefully it is just a case they they just need to be verified as invalid.
